spring:
  application:
    name: lead.magnet
  datasource:
    url: "jdbc:postgresql://localhost:5433/magnet"
    username: "magnet"
    password: "magnet"

  liquibase:
    change-log: "/db/changelog/changelog.xml"
